{
  "DATA": {
    "dataset_dir": "/media/data2/MLICdataset/",
    "dataname": "voc2007partial",
    "num_workers": 8,
    "prob": 0.5,
    "num_class": 20,
    "len_train_loader": -1,
    "classnames": [
      "aeroplane",
      "bicycle",
      "bird",
      "boat",
      "bottle",
      "bus",
      "car",
      "cat",
      "chair",
      "cow",
      "diningtable",
      "dog",
      "horse",
      "motorbike",
      "person",
      "pottedplant",
      "sheep",
      "sofa",
      "train",
      "tvmonitor"
    ],
    "TRANSFORM": {
      "img_size": 448,
      "crop": false,
      "cutout": true,
      "length": 224,
      "cut_fact": 0.5,
      "orid_norm": false,
      "remove_norm": false,
      "n_holes": -1
    }
  },
  "INPUT": {
    "SIZE": [
      448,
      448
    ],
    "INTERPOLATION": "bicubic",
    "TRANSFORMS": [
      "random_resized_crop",
      "MLC_Policy",
      "random_flip",
      "normalize"
    ],
    "NO_TRANSFORM": false,
    "PIXEL_MEAN": [
      0.48145466,
      0.4578275,
      0.40821073
    ],
    "PIXEL_STD": [
      0.26862954,
      0.26130258,
      0.27577711
    ],
    "CROP_PADDING": 4,
    "CUTOUT_N": 1,
    "CUTOUT_LEN": 16,
    "GN_MEAN": 0.0,
    "GN_STD": 0.15,
    "RANDAUGMENT_N": 2,
    "RANDAUGMENT_M": 10,
    "COLORJITTER_B": 0.4,
    "COLORJITTER_C": 0.4,
    "COLORJITTER_S": 0.4,
    "COLORJITTER_H": 0.1,
    "RGS_P": 0.2,
    "GB_P": 0.5,
    "GB_K": 21,
    "random_resized_crop_scale": [
      0.5,
      1.0
    ],
    "cutout_proportion": 0.4,
    "TRANSFORMS_TEST": [
      "resize",
      "normalize"
    ]
  },
  "MODEL": {
    "arch": "DualCoop",
    "use_BN": false,
    "BACKBONE": {
      "backbone": "RN101",
      "pretrained": true,
      "frozen_backbone": false
    },
    "TRANSFORMER": {
      "enc_layers": 1,
      "dec_layers": 2,
      "dim_feedforward": 8192,
      "hidden_dim": 2048,
      "dropout": 0.1,
      "nheads": 4,
      "pre_norm": false,
      "position_embedding": "v2",
      "keep_other_self_attn_dec": false,
      "keep_first_self_attn_dec": false,
      "keep_input_proj": false
    },
    "CLASSIFIER": {
      "num_class": 20
    },
    "CAPTION": {
      "n_ctx_pos": 16,
      "n_ctx_neg": 16,
      "csc": true,
      "ctx_init_pos": "",
      "ctx_init_neg": "",
      "class_token_position": "end",
      "gl_merge_rate": 0.5,
      "n_ctx": 16,
      "ctx_init": ""
    }
  },
  "LOSS": {
    "loss_dev": -1,
    "loss_mode": "dualcoop",
    "ASL": {
      "eps": 1e-05,
      "dtgfl": true,
      "gamma_pos": 0.0,
      "gamma_neg": 2.0,
      "loss_clip": 0.0
    },
    "DUALCOOP": {
      "eps": 1e-08,
      "dtgfl": true,
      "gamma_pos": 1.0,
      "gamma_neg": 2.0,
      "loss_clip": 0.05,
      "thresh_pos": 0.9,
      "thresh_neg": -0.9
    }
  },
  "OPTIMIZER": {
    "optim": "AdamW",
    "lr_scheduler": "OneCycleLR",
    "pattern_parameters": "single_lr",
    "momentum": 0.9,
    "sgd_dampening": 0,
    "sgd_nesterov": false,
    "weight_decay": 0.0005,
    "max_clip_grad_norm": 0,
    "epoch_step": [
      10,
      20
    ],
    "batch_size": 64,
    "lr": 0.001,
    "lrp": 0.1,
    "lr_mult": 1.0,
    "warmup_scheduler": false,
    "warmup_type": "linear",
    "warmup_epoch": 0,
    "warmup_lr": 1e-05
  },
  "DDP": {
    "world_size": 1,
    "rank": 0,
    "dist_url": "env://",
    "local_rank": 0,
    "gpus": 0,
    "seed": 1
  },
  "TRAIN": {
    "seed": 1,
    "amp": true,
    "early_stop": true,
    "kill_stop": false,
    "device": "cuda",
    "start_epoch": 0,
    "epochs": 80,
    "ema_decay": 0.9998,
    "ema_epoch": 0,
    "evaluate": false
  },
  "INPUT_OUTPUT": {
    "output": "checkpoint/dualcoop/voc2007/adam/work2/pro05",
    "resume": "",
    "resume_omit": [],
    "print_freq": 10,
    "out_aps": false
  },
  "EVAL": {
    "val_interval": 1
  }
}